/*
  ==============================================================================

  This file was auto-generated by the Introjucer!

  It contains the basic startup code for a Juce application.

  ==============================================================================
  */

#include "PluginProcessor.h"
#include "PluginEditor.h"

//==============================================================================
RemoteGoatVstAudioProcessorEditor::RemoteGoatVstAudioProcessorEditor(RemoteGoatVstAudioProcessor* ownerFilter)
: AudioProcessorEditor(ownerFilter)
{
	// This is where our plugin's editor size is set.
	setSize(400, 300);
}

RemoteGoatVstAudioProcessorEditor::~RemoteGoatVstAudioProcessorEditor()
{
}

//==============================================================================
void RemoteGoatVstAudioProcessorEditor::paint(Graphics& g)
{
	g.fillAll(Colours::white);
	g.setColour(Colours::black);
	g.setFont(15.0f);

	// Get audio processor.
	auto* pu = getAudioProcessorTyped();

	// Write trace lines.
	const auto& trace = pu->getTrace();
	int i = 0;
	for (const String& line : trace)
	{
		g.drawText(line, 0, i * 15, getWidth(), 15, Justification::left, true);
		++i;
	}
}

//==============================================================================
RemoteGoatVstAudioProcessor* RemoteGoatVstAudioProcessorEditor::getAudioProcessorTyped() const
{
	return (RemoteGoatVstAudioProcessor*)getAudioProcessor();
}
